server:
    port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbisimm?useSSL=false&serverTimezone=UTC
    username: root # Replace with your MySQL username
    password: boussetta1234 # Replace with your MySQL password
  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update # Auto-create tables; set to validate or none in production
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
